### ISSUE TITLE
UnhandledPromiseRejectionWarning: HttpError: Bad credentials

### ISSUE THREAD

**Issue by DanielTamkin** [octokit/core.js#149]
When purposfully attempting to instantiate a class with a bad token, i expect to be able to catch the error and handle accordingly. However this is not the case, while i do catch the error... the node error `UnhandledPromiseRejectionWarning` is thrown from inside the `core.js` module. 

To illustrate, this is a snippet in the auth check im performing.
Worst case scenario: Set state to error and reject.
Best case scenario: Set state to ready and resolve.

```javascript
          this.octokit = await new Octokit({
            auth: this.config.GITHUB_TOKEN,
          });
          this.octokit.request('/user')
            .then((data) => {
              this.user = data;
              this.setState('ready');
              resolve();
            })
            .catch((err) => {
              this.setState('error', {
                message: err.message,
                data: err,
              });
              // Catch errors
              reject(err);
            });

```

The result is neither, the rejection is not caught. Instead node throws an the error mentioned above.
![image](https://user-images.githubusercontent.com/9532762/89094071-fb647f80-d385-11ea-8e02-0ff3c5dca57e.png)

Very curious into the workarounds with this, not noticing this error on some other repos i've tracked down. Possibly a babel mis-configuration on my end? Regardless i can't be the only one looking to auth check tokens prior to making a bunch of requests hoping the tokens are valid.

**Comment by gr2m** [comment]
You don't need the `await` before `new Octokit()`

Here is a minimal test case that works as intended:
https://runkit.com/gr2m/octokit-core-js-149

I tested the same locally, too. There is no `UnhandledPromiseRejectionWarning`.

I'm quite certain it originates from a different place in your code base.
