### ISSUE TITLE
Improve error handling by adding types for Octokit error

### ISSUE THREAD

**Issue by sqren** [octokit/core.js#156]
Hi there,

I'm trying to handle the errors from Octokit but I'm not able to find docs (or better: types) for the errors that can be thrown.
As an example, this is how I hoped I'd be able to get a typed error:

```ts
try {
    const octokit = new Octokit(...);
    return await octokit.search.commits(...);
} catch(e) {
  if(e instanceof OctokitError) {
    // `e` will now be typed
  }
}
```

But I can't find anything like `OctokitError` in the types. I can add my own error type like:

```ts
type OctokitError = {
  name: string;
  status: number;
  documentation_url: string;
  errors?: Array<{
    resource: string;
    code: string;
    field: string;
    message?: string;
  }>;
};
```

Is there a concrete contract for errors I can see somewhere to ensure above type is correct? I looked in [the docs](https://developer.github.com/v3/#client-errors) and they seem incorrect (or out of date):

<img width="500" src="https://user-images.githubusercontent.com/209966/89431818-b2734900-d740-11ea-9d59-b9582f5fd93a.png" />

See for example this error I got back from `octokit.search.commits`:

<img width="500" src="https://user-images.githubusercontent.com/209966/89431862-c028ce80-d740-11ea-8cd3-1d059390c9ba.png" />

Notice how there is a `message` in: `e.errors[i].message` where the docs only mentions `e.message`.

**Comment by gr2m** [comment]
We could add an OctokitRequestError type to https://github.com/octokit/types.ts/tree/master/src, so you can import it from `@octokit/types`.

I don't think it's currently possible to set types for errors that can be thrown by a method (https://github.com/microsoft/TypeScript/issues/13219), that'd be cool though

**Comment by gr2m** [comment]
could you send a pull request to https://github.com/octokit/types.ts/?

**Comment by sqren** [comment]
@gr2m Done!
