### ISSUE TITLE
Browser-side plugins

### ISSUE THREAD

**Issue by aensley** [octokit/core.js#17]
Thanks to Pika.dev for providing an easy way to use this library from the browser.

I'm following this pattern

```html
<script type="module">
import { Octokit } from "https://cdn.pika.dev/@octokit/core";
</script>
```

And it works.

However, I don't seem to be able to use any plugins this way. `require()` doesn't exist browser-side.

```javascript
import { Octokit } from 'https://cdn.pika.dev/@octokit/core'
const octokit = new Octokit({
  auth: '1234',
  baseUrl: 'https://mygithubenterprise.com/api/graphql',
  previews: ['cloak-preview', 'mercy-preview']
}).plugin([
  require('@octokit/graphql')
])
```

Result:

```
Uncaught ReferenceError: require is not defined
```

How can I use plugins from the browser?

**Comment by gr2m** [comment]
Unfortunately the plugins are not yet published to Pika, but it's something I'm working on right now.

[`@octokit/graphql`](https://github.com/octokit/graphql.js) is no a plugin though, it's a standalone library. But the good news is that it's already built into `@octokit/core`, so you can just do this:

```js
import { Octokit } from 'https://cdn.pika.dev/@octokit/core'
const octokit = new Octokit({
  auth: '1234',
  baseUrl: 'https://mygithubenterprise.com/api/graphql',
  previews: ['cloak-preview', 'mercy-preview']
})
octokit.graphql(`... your query here ...`)
```

Does that work for you?

**Comment by gr2m** [comment]
OH, I just realized that the `baseUrl` option might be a problem with GitHub Enterprise. I'll look into fixing it, but for the time being, try to set it to just `https://mygithubenterprise.com/api`

**Comment by aensley** [comment]
@gr2m Thanks for the replies. I was going off of this comment on [`@octokit/graphql`](https://github.com/octokit/graphql.js/): https://github.com/octokit/graphql.js/issues/61#issuecomment-541906082

Basically, I want to paginate graphql queries without having to write a lot of code. I'm also interested in using the retry and throttling plugins, so my basic question is still unanswered. Assuming the plugins were on Pika, how would I use them from the browser?

**Comment by gr2m** [comment]
Assuming the plugins were on Pika, you would use them like this

```html
<script type="module">
import { retryPlugin } from "https://cdn.pika.dev/@octokit/plugin-retry";
import { throttlePlugin } from "https://cdn.pika.dev/@octokit/plugin-throttling";
import { Octokit } from "https://cdn.pika.dev/@octokit/core";

const MyOctokit = Octokit.plugin([retryPlugin, throttlePlugin])
const octokit = new MyOctokit()
</script>
```

Note that the throttle plugin will not be helpful for GraphQL at this point, it has its own rate limiting independent of http requests.

And for retries, I was told to try a graphql request once in case in timed out, as a temporary index might have been created and the 2nd request might be able to respond within the 10s timeout. That is currently not implemented in the retry plugin.

I'll happily take pull requests that make the plugins pika-compatible. Here is a plugin that can be used as reference: https://github.com/octokit/plugin-paginate-rest.js. I cannot work on it myself until the next year, I'm afraid

> I want to paginate graphql queries without having to write a lot of code

I did not found a simple solution for that bit yet. I've shared some insights in my comment here: https://github.com/octokit/graphql.js/issues/61#issuecomment-555316014

**Comment by aensley** [comment]
@gr2m That makes sense. I'm afraid much of this is out of my league (I'm not really a JS/ES/TS dev), so I'll wait patiently for a solution. Thanks for the explanation and all your work on this project. It has really helped me.

**Comment by gr2m** [comment]
All the plugins are now published to pika, the code shown above should just work :tm: Let me know if you run into any problems
