### ISSUE TITLE
To add `javascript` as topic

### ISSUE THREAD

**Issue by oscard0m** [octokit/core.js#247]
**What’s missing?**
To add `javascript` as topic

**Why?**
When filtering Octokit repos by `javascript` topic would be nice to get all the ones using JS as language

**Alternatives you tried**

Nothing to try

**Comment by gr2m** [comment]
you can filter using `language:javascript language:typescript`: https://github.com/search?q=org%3Aoctokit+language%3Ajavascript+language%3Atypescript

**Comment by gr2m** [comment]
but we can still add a `javascript` topic, why not 👍🏼

**Comment by natasha1007** [comment]
underpre  ssure  01/special- octo - fiesta #371
