### ISSUE TITLE
   TypeError: isPlainObject.isPlainObject is not a function      > 1 | import { Octokit } from "@octokit/core";

### ISSUE THREAD

**Issue by tanay-pingalkar** [octokit/core.js#311]
**What happened?**

**What did you expect to happen?**

**What the problem might be**

**Comment by tanay-pingalkar** [comment]
I uninstall the package and installed it again, and it works for me

**Comment by ne-v0y** [comment]
Same thing happened to me and reinstallation didn't work. I ended up adding `is-plain-object` as a dpendency.
