### ISSUE TITLE
`GET /user/emails` returns 404

### ISSUE THREAD

**Issue by matthewchung74** [octokit/core.js#338]
I'm trying to implement this https://api.github.com/user/emails , currently with postman.
However, when including my bearer token, I get a 
```
{
    "message": "Not Found",
    "documentation_url": "https://docs.github.com/rest/reference/users#list-email-addresses-for-the-authenticated-user"
}
```

I can make a request using the same bearer token to https://api.github.com/user and get results.

**What did you expect to happen?**

I expected to get a result like 
```
[
  {
    "email": "octocat@github.com",
    "verified": true,
    "primary": true,
    "visibility": "public"
  }
]
```

**Comment by matthewchung74** [comment]
@gr2m thanks for responding. I think I didn't include enough detail before. My app is an OAuth App, and I don't see a place to specify the scope via Developer settings->Oauth Apps. When going through OAuth Web application flow https://docs.github.com/en/developers/apps/authorizing-oauth-apps#web-application-flow, I can see the scope returned in the response, but no where to request the scope. Any suggestions?

**Comment by gr2m** [comment]
In step 1 one of the web application flow you have to pass a `?scope` query parameter, as described here:

https://docs.github.com/en/developers/apps/authorizing-oauth-apps#1-request-a-users-github-identity

<img width="937" alt="image" src="https://user-images.githubusercontent.com/39992/118738193-4d826e80-b7fb-11eb-88fb-1433506b2d12.png">

The OAuth App itself has no scopes, the scopes are set for each OAuth flow.

If you are building an OAuth app, you might be interested in https://github.com/octokit/oauth-app.js, it has some useful helper methods. We also maintain a set of stateless functions you can use for all things OAuth: https://github.com/octokit/oauth-methods.js/

**Comment by matthewchung74** [comment]
Sorry, I'm not sure how I missed that. Thanks and I'll check out `oauth-app.js`.
