### ISSUE TITLE
Convert `type OctokitOptions` to `interface OctokitOptions`

### ISSUE THREAD

**Issue by oscard0m** [octokit/core.js#449]
**What’s missing?**

To convert `type OctokitOptions` to `interface OctokitOptions` would open the door to make more accurate types for Octokit Plugins with specific required options like [`@octokit/plugin-throttling`](https://github.com/octokit/plugin-throttling.js):

https://github.com/octokit/plugin-throttling.js/blob/c567474ff2f6959a460d1139959052ec70a791a6/src/types.ts#L10-L20

**Why?**

When trying to deprecate a property for the `option` object provided to `@octokit/plugin-throttling` I noticed there is not a good typing to be able to do so.

Also, we are missing all the benefits from a good TS typing for this and other plugins (auto-completion, catch errors on build time, etc...)

**Alternatives you tried**
You can see this draft PR (https://github.com/octokit/plugin-throttling.js/pull/457) where we did a bit of experimentation but @G-Rath [come up with a great solution](https://github.com/octokit/plugin-throttling.js/pull/457#issuecomment-1057276708) which implies this change in `@octokit/core.js` types:

**Comment by Mohm730** [comment]
في الخميس، ٣ مارس ٢٠٢٢ ٨:١٨ م Oscar Dominguez ***@***.***>
كتب:
