### ISSUE TITLE
[Maintenance] automated release failed

### ISSUE THREAD

**Issue by gr2m** [octokit/core.js#451]
See https://github.com/octokit/core.js/runs/5412497631?check_suite_focus=true. Any idea what might have happened?

**Comment by KAMORU9** [comment]
I need making sure that done all of the issue Document professional and the problem devil is in my account today I need to get that bills payment accept thrive tome today

**Comment by wolfy1339** [comment]
This isn't the first time this has happened.

When trying it out locally, I found that using `pika-pack` works.

That's also how it is defined in their `package.json`

https://unpkg.com/browse/@pika/pack@0.5.0/package.json

**Comment by oscard0m** [comment]
I will take a look into it next week.

**Comment by oscard0m** [comment]
Seems like `pika` is kind of unmaintained:
https://github.com/withastro/pack/issues/91#issuecomment-847139938

Do you mind if I open a discussion under octokit.js on how how we should be building Octokit projects from now on?

If not, I guess we will need task for migrating (with Octoherd?) all the scripts to `pika-pack`

**Comment by gr2m** [comment]
> how how we should be building Octokit projects from now on

basically how https://github.com/octokit/octokit-next.js is built: everything is written as ES Module JavaScript, no more build step at all. `d.ts` files are written by hand.

**Comment by gr2m** [comment]
👆🏼yay
