### ISSUE TITLE
[TypeScript] REST API route completion is not triggered

### ISSUE THREAD

**Issue by HoTKreeZy** [octokit/core.js#469]
**What happened?**

API route completion is not triggered when I use the `octokit.request()`

**What did you expect to happen?**

When starting to write the API route, I was expecting to have an API route completion but I don't.
I found (unexpectedly) that using a new pair of parenthesis when calling the method, I do get an API route completion.

**How it should be ;**
```js
const octokit = new Octokit({ auth: `personal-access-token123` });

const response = await octokit.request(
    "GET /orgs/{org}/repos",
    {
          org: "octokit",
          type: "private",
    }
);
```

**What I have to do ;**
```js
const octokit = new Octokit({ auth: `personal-access-token123` });

const response = await octokit.request(
    ("GET /orgs/{org}/repos"),
    {
         org: "octokit",
         type: "private",
    }
);
```

**Comment by wolfy1339** [comment]
Can you share some more details regarding your setup?
Editor and editor version, OS, NodeJS version

**Comment by wolfy1339** [comment]
I'm not sure this a bug with our code. This simply looks like an oddity with how the typescript types are processed and auto complete

**Comment by HoTKreeZy** [comment]
I'm using the latest version of Vscode (v1.68.1) on Windows 10.

I'm using NodeJS version 18.3.0.

**Comment by gr2m** [comment]
I observed the same problem myself, it's very odd! And i was able to confirm that your mention workaround using `()` as in `("GET /orgs/{org}/repos")` works! It feels to me like a bug with VS Code, but I thought it was still working a few days back and suddenly the behavior began. 

I'd very much appreciate any help with digging into this

**Comment by wolfy1339** [comment]
> It feels to me like a bug with VS Code

The same problem happens on the Typescript Playground, I don't think it's limited to VS Code

**Comment by gr2m** [comment]
This is so funky. Here is the [TypeScript playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzlApgRwK4oM7wL5wBmUEIcARAAIQDGMEA1sDAPSqY4zkCwAUHyxZxsKeDQxRs0OACNRAdxQoAdhXIAaODAAWKuGFTZscOlAA2cANTCwAQxoo+7LLgAU5cgEo4g5BAwwOHC2qHDKEPDYGADm0ZwoACaaMgFa2rbwGCIJWhBw8tAMTuguMK7uXt6+OsDGBVAM2JqE0vLpgQBuKFDIKLZSypoAEgCCADIACgCEQA) to experiment, and a video recording to showcase the problem

https://user-images.githubusercontent.com/39992/174911586-64cc7665-ffa3-4255-bf90-7f55fc7ec4a7.mov

**Comment by gr2m** [comment]
Some insights by @levenleven

> it works if you switch to earlier TypeScript version
[Playground](https://www.typescriptlang.org/play?ts=4.6.4#code/JYWwDg9gTgLgBAbzlApgRwK4oM7wL5wBmUEIcARAAIQDGMEA1sDAPSqY4zkCwAUHyxZxsKeDQxRs0OACNRAdxQoAdhXIAaODAAWKuGFTZscOlAA2cANTCwAQxoo+7LLgAU5cgEo4g5BAwwOHC2qHDKEPDYGADm0ZwoACaaMgFa2rbwGCIJWhBw8tAMTuguMK7uXt6+OsDGBVAM2JqE0vLpgQBuKFDIKLZSypoAEgCCADIACgCEQA)

and

> It seems to work if you split https://github.com/octokit/types.ts/blob/master/src/RequestInterface.ts#L26-L33 to two overloads: one for known routes (keyof Endpoints) and another one for "catch" all string
[Playground](https://www.typescriptlang.org/play?#code/PTAEEsFsAcHsCcAuoDep4FMCOBXDBnZAX1ADN5ZJQAiAAVgGNFYBrcRYTXAxagWABQgkKBH4MyBjnj4EoAEYSA7hgwA7GtQA0oRAAt1oaJnz5QTeABtQAalD5oAQwYZhYLnkIAKatQCUou6wOIgEoI6YoGqwyPg4AObxPBgAJjryIbp6jsg44im6sKBKCCxu6NieiF4+-gEi+uBmJfAs+DqkckrZoQBuGPAVjrJqOgASAIIAMgAKAISCiwKIAJ7QGKAASsGhZgC8qKAA5ADiAKIAKqAAGkcAXMdHOqeXoACa94+gRIKr61s7DYHQjwcBqeJLFIYBiWCIbUg4NRMcCwDQeHgAHk2oAwAA9QmoUmYWBgVrBSACQgQAHxeChUh6bPwPXqwcApADcgihMLhZERyNRFW43npoUZgOZoFZ7K5Qnl6O8vj8QA)

**Comment by HoTKreeZy** [comment]
While the PR has fixed the route completion, it looks like the PR has broke options completion

**Comment by timrogers** [comment]
@HoTKreeZy Oh dear! 😬 Would you mind creating a new issue so we can track what you’re seeing?
