### ISSUE TITLE
No type information added to Octokit instance when using an array of plugins.

### ISSUE THREAD

**Issue by MaximDevoir** [octokit/core.js#51]
**Bug**

No type information is added to an Octokit instance when using an array of plugins where one of the plugins return value is set to `void` or an empty object `{}`.

**Example**

```TypeScript
import { Octokit } from '@octokit/core'

declare function requestLog(octokit: Octokit): void;
declare function paginateRest(octokit: Octokit): { paginate: ...};
declare function queueWorker(octokit: Octokit): { add: ...};

// TypeScript is able to add methods provided by `paginateRest` and `queueWorker` plugins to the API instance for type-hinting/checking.
const API = new (Octokit.plugin(requestLog).plugin([paginateRest, queueWorker]))()

// API below is missing methods provided by `paginateRest` and `queueWorker` plugins.
const API = new (Octokit.plugin([requestLog, paginateRest, queueWorker]))()
```

**Explanation**
Because `() => void` is a supertype of any plugin that returns an object, TypeScript will widen/simplify the type of `plugins` to `() => void`, resulting in a loss of type information.

Minimal repro on [TS Playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtVIDUctgAKASgC54A3Y4AKFElgRXWzyQDEccLqAbyR9qARngBfJuGhwkaTLnyIAQrAHxhAI1jUATFIYMA9CfgAJHDRAx4127VhYo2iCADO8bSAg4A7vAYOLRYIIFYqIi2IMBOEMieAHQMYHgeGPCoODAAtlAQAJJRMegIALzwANqIvDgANEjqMAC6qemZ-iQgqLHF0XBl8JU1dY2IRCRtQA).

**Workarounds**
To prevent a loss of type information when adding plugins to your Octokit instance: do not mix plugins that return an object filled with properties with non-object-property-filled plugins (e.g. `void` or empty objects `{}`) in the same `.plugin()` call.

Turn this: `Octokit.plugin([() => void, () => {}, paginateRest, queueWorker])`

into: `Octokit.plugin([() => void, () => {}]).plugin([paginateRest, queueWorker])`

**Solutions**

1. ~~We could add an overload to the `plugin` function to separate plugins returning void from plugins returning filled objects.~~ This won't solve the issue because plugins returning an empty object will continue to widen the array of plugin type information to `() => {}` and I don't think TypeScript is able to separate an empty object from a filled object.

2. ~~Similar to above, add an overload for `void` plugins. For `.plugin([])` calls that mix filled objects with empty objects, log an error to the console that returning empty objects messes up the type information and that the empty object must be placed in its own `.plugin()` call.~~ No way in TypeScript to differentiate between a filled object and an empty object.

**Comment by MaximDevoir** [comment]
This explains why, for Octokit/rest, we can't just do `.plugin([requestLog, paginateRest, restEndpointMethods])` in one call (see [here](https://github.com/octokit/rest.js/blob/master/src/index.ts#L9-L15)).

Because `requestLog` doesn't return anything, and is mixed in with plugins that return non-empty objects, the plugins array from the call is simplified as the void supertype.


Similar to octokit/rest.js#1625. @wolfy1339 octokit/rest.js#1625 can be closed because the *void* plugin is already separated from the plugins returning non-empty objects.

**Comment by gr2m** [comment]
> octokit/rest.js#1625 can be closed because the void plugin is already separated

The separation is really a workaround that I want to get rid of. I've created a smaller reproducible test case here: https://github.com/gr2m/javascript-plugin-architecture-with-typescript-definitions/pull/15 What surprised me is that even if the return is `{}` you see the same problem, it's not only when the return value is `void`. 

I basically extracted the plugin architecture from Octokit into https://github.com/gr2m/javascript-plugin-architecture-with-typescript-definitions so others can use it for their own project. I think it would be simplest to investigate the problem there, as there are no other features that might interfere in the code base

**Comment by MaximDevoir** [comment]
I think the issue of the `{}` has to do with a long-time bug in TS - see microsoft/TypeScript#241. Basically, in certain scenarios, the return value types from function expressions will be widened.

I somewhat alluded to this above, an array of functions whose return values are a combination of filled objects and empty objects will get inferred and simplified to the empty object (aka `{}`).

You can see TS simplify the return values from functions in an array from the playground link below.

[TS Playground](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=12&pc=2#code/PTAEAkHsDcFMCdQwaAtgT1NAhvAltgEYA2soAdtqrALABQAxpOQM4Auoe5AZgvLABMAgiwCiADwAOsBm0GgAvKADa9UKAAUASkUA+UAG9Q-NgFd45Q6GwAuUAHIAjPdABfNwBo1mnQv1GTc0sjQjt7ACYXd1d6AF16ehAIZEQUtEwcfCJSCipaRmZ2Th4EWHIGWAB1PAEy+SVVOnVtPStAiytbB2c3T28WvzbYMw6QsMje1y8mn1aA4aDDaNA4oA)

```TypeScript
// TS: const inferredAsExpected: ((() => {
//    a: string;
// }) | (() => {
//    b: string;
// }))[]
const inferredAsExpected = [
  () => { return { a: '1' } },
  () => { return { b: '2' } }
]

// TS: const inferenceWidened: (() => {})[]
const inferenceWidened = [
  () => { return { a: '1' } },
  () => { return { b: '2' } },
  () => { return {} } 
]
```


As for workarounds, I don't think there are any :slightly_frowning_face:. The array of plugins will always be simplified by TypeScript.

What we can do is require that `void` return types must be placed in their own `.plugin()` call and separate from the plugins that return an object. To solve the issue of a plugin possibly returning an empty object, an error would be logged to the console detailing that the empty object is destroying typeahead from other plugins and that the plugin may not return an empty object.

Another option would be to require at least one property from the plugin in the returned object. That way TypeScript won't simplify the plugins array return values.

**Comment by gr2m** [comment]
Thanks a lot for the thorough explanation, I'm learning a lot 👨‍🎓️

So I guess TypeScript has a bug with type inference from an array of objects, and there is not much we can do?

I wonder if we could something in our implementation to work around it? E.g. we could merge the result of the plugin function with a default object, so that we can guarantee that we always have an object, sth like this?

```ts
function mapToObjectReturn(func: Plugin) {
  return () => Object.assign({ tsWorkaround: undefined }, func())
}
```

So the inference would not be using the direct result of the plugin function, but the result + `{ tsWorkaround: undefined }`

I'm just thinking out loud 🤔

**Comment by MaximDevoir** [comment]
That would have to be something the user loading the plugins would have to do - which isn't ideal - and must be done before the plugins are placed into an array (read: before TS widens the inferred type of the array of plugins).

As far as I can tell, nothing could be implemented internally into octokit/core.js using TypeScript's type system to solve this issue. I don't think there is a pretty solution to this.

I think to make this easiest for consumers of plugins, we require at least one object with one property to be returned. For simplicity, let's say we'll require the `plugin-name` property. This guarantees that users don't have to worry if grouping another plugin to the array of plugins will break typeahead of not. This known property can be removed from the plugin before it's added to the Octokit instance as well as removed from being suggested from typeahead.
