### ISSUE TITLE
Unfollow request with GitHub's REST api is giving me an error.

### ISSUE THREAD

**Issue by mrdcvlsc** [octokit/core.js#511]
**What happened?**

I was trying GitHub's [rest API for followers](https://docs.github.com/en/rest/users/followers) using **octokit.js** and everything (e.g. getting the **lists** of: **followers**, **followings**, and using the API to **follow a user**) seems to work fine until tried the **[unfollow request shown in the unfollow section](https://docs.github.com/en/rest/users/followers#unfollow-a-user)**:

```js
const octokit = new Octokit({
  auth: PERSONAL_ACCESS_TOKEN
})

const unfollow = await octokit.request('DELETE /user/following/userToUnfollow', {
  username: 'userToUnfollow'
})
```

but it's giving me error

```js
RequestError [HttpError]: Invalid request.

"username" is not a permitted key.
    at /home/$USER/node_apps/gh-rest-test-project/node_modules/@octokit/request/dist-node/index.js:88:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/home/$USER/node_apps/gh-rest-test-project/index.js:32:20) {
  status: 422,
  response: {
    url: 'https://api.github.com/user/following/userToUnfollow',
    status: 422,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      'content-length': '153',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Mon, 05 Sep 2022 04:09:57 GMT',
      'github-authentication-token-expiration': '2022-09-11 22:58:51 UTC',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': 'repo',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'FFFF:FFFF:FFFFFF:FFFFFF:FFFFFFFF',
      'x-oauth-scopes': 'user',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4984',
      'x-ratelimit-reset': '1662352636',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '16',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Invalid request.\n\n"username" is not a permitted key.',
      documentation_url: 'https://docs.github.com/rest/reference/users#unfollow-a-user'
    }
  },
  request: {
    method: 'DELETE',
    url: 'https://api.github.com/user/following/userToUnfollow',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/4.0.5 Node.js/18.8.0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"username":"userToUnfollow"}',
    request: { hook: [Function: bound bound register] }
  }
}
```

Every examples in the [documentation](https://docs.github.com/en/rest/users/followers) is working fine, The **unfollow a user** section with octokit.js is the only one giving me problems.

Also the **cURL** version for **unfollowing a user** is working so I think the problem might be in octokit itself? or the documentation is wrong? or I'm using the API wrong?

**Comment by timrogers** [comment]
@mrdcvlsc Thanks for reaching out! Can you try this code instead?:

```js
const unfollow = await octokit.request('DELETE /user/following/{username}', {
  username: 'userToUnfollow'
})
```

If you want to rename the `username` variable to `userToUnfollow`, it would look like this:

```js
const unfollow = await octokit.request('DELETE /user/following/{userToUnfollow}', {
  userToUnfollow: 'userToUnfollow'
})
```

I hope that helps ✨ It sounds like there might have been a confusing example somewhere - let me know where you found it and I'll get it fixed.

**Comment by mrdcvlsc** [comment]
@timrogers thanks for the reply and for showing how to rename the key variable properly, unfortunately though when I tried your first example, it's giving me a new error:

```js
const unfollow = await octokit.request('DELETE /user/following/{username}', {
  username: 'userToUnfollow'
})
```

**Error**

```js
/home/$USER/node_apps/gh-rest-test-project/node_modules/@octokit/request/dist-node/index.js:110
    throw new requestError.RequestError(error.message, 500, {
          ^

RequestError [HttpError]: fetch failed
    at /home/$USER/node_apps/gh-rest-test-project/node_modules/@octokit/request/dist-node/index.js:110:11
    at async main (/home/$USER/node_apps/gh-rest-test-project/index.js:34:20) {
  status: 500,
  request: {
    method: 'DELETE',
    url: 'https://api.github.com/user/following/userToUnfollow',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/4.0.5 Node.js/18.8.0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-length': 0
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

It still works when **[following a user with PUT request](https://docs.github.com/en/rest/users/followers#follow-a-user)** using JavaScript Octokit, but not when I'm **[unfollowing a user with DELETE request](https://docs.github.com/en/rest/users/followers#unfollow-a-user)**

**Comment by timrogers** [comment]
I believe that this is a known issue with `fetch` when you make DELETE requests through Octokit. Which Node version are you using?

**Comment by mrdcvlsc** [comment]
Oh I see that's unfortunate then, I'm using **v18.8.0** of node

**Comment by timrogers** [comment]
I've just made a PR, `https://github.com/octokit/endpoint.js/pull/354`, which should fix the underlying bug.

**Comment by timrogers** [comment]
This should now be fixed if you update to the latest `octokit/endpoint.js`. Can you give it a go? I'm going to close this issue assuming that it's working, but if it doesn't fix it, do feel free to reopen.

**Comment by mrdcvlsc** [comment]
> This should now be fixed if you update to the latest `octokit/endpoint.js`. Can you give it a go? I'm going to close this issue assuming that it's working, but if it doesn't fix it, do feel free to reopen.

@timrogers thanks, it's now working!
