### ISSUE TITLE
[BUG]: can not intercept requests with nock

### ISSUE THREAD

**Issue by mac2000** [octokit/core.js#551]
### What happened?

Suddenly all tests depending on nock starts to fail

```bash
mkdir foo
cd foo
npm init -y -f
npm i -S @octokit/rest nock
```

**demo.js**

```js
const { Octokit } = require('@octokit/rest')
const nock = require('nock')
const fetch = require('node-fetch')

nock.recorder.rec()
nock("https://api.github.com")
      .post("/graphql")
      .reply(200, {data: {hello: "world"}});

const octokit = new Octokit({request:{fetch}})
octokit.graphql(`{ whatever }`)
    .then(res => console.log(res))
    .catch(err => console.log(err.message)) // This endpoint requires you to be authenticated
```

Instead of expected, mocked response I'm receiving and error "This endpoint requires you to be authenticated"

Which makes me believe tests like this [1323-parameter-deprecation-bug-test.js](https://github.com/octokit/rest.js/blob/main/test/issues/1323-parameter-deprecation-bug-test.js) will also fail

Meanwhile, node complains:

```log
(node:41108) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

When enabling trace warning as node suggests I see this piece of code in @octokit/request.js:

```js
const fetch = requestOptions.request && requestOptions.request.fetch || globalThis.fetch || /* istanbul ignore next */nodeFetch;
```

and indeed if I will put nodeFetch in first place, suddenly everything  starts to work

current workaround is already suggested somewhere in [stackoverflow](https://stackoverflow.com/a/75196306/1168586)

so we may want to do something like this (note that request.js library depends on node-fetch):

```js
const fetch = require('node-fetch')
const octokit = new Octokit({request:{fetch}})
```

### Versions

"@octokit/rest": "^19.0.7"
"nock": "^13.3.0"

node: v18.5.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
The latest Node comes with a built-in `fetch` which cannot be intercepted by `nock`, I think. 

I would recommend to mock with `fetch-mock` instead, like this: https://github.com/octokit/core.js/blob/72c8bc70fb9d9b4be75379e6e8a5a31877bf03a3/test/request.test.ts#L15-L28

**Comment by kfcampbell** [comment]
Closing as the question has been answered. Please open additional issue(s) for additional questions.
