### ISSUE TITLE
[BUG]: OctokitOptions declared locally but not exported

### ISSUE THREAD

**Issue by mcgear** [octokit/core.js#645]
### What happened?

I am trying to use OctokitOptions in a typescript project for DenoJS, but am getting the following error when using this import `import { OctokitOptions } from "@octokit/core";`

![image](https://github.com/octokit/core.js/assets/1460046/a711f4c2-aa93-4f04-b1af-3204348078e1)

Not sure how to handle, thanks for the help.

### Versions

octokit/core: https://esm.sh/@octokit/core@v5.0.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
You are getting that error because that export does not exist.

It's imported in the `index.ts` file but not exported.

If you absolutely need to import it, you can use:

```ts
import type from "@octokit/core/dist-types/types.d":
```

**Comment by mcgear** [comment]
Its mostly for cleanliness of some helper functions we are establishing for Octokit initialization. Any plans to add this as an export? Would it be an accepted PR?

**Comment by mcgear** [comment]
Its mostly for cleanliness of some helper functions we are establishing for Octokit initialization. Any plans to add this as an export? Would it be an accepted PR?

**Comment by wolfy1339** [comment]
You can also do this:
```ts
type OctokitOptions = ConstructorParameters<Octokit>;
```

I'm open to a PR

**Comment by mcgear** [comment]
Created PR #646
