### ISSUE TITLE
[BUG]: The type of 'data' field in OctokitResponse type is an object but type hinting show it's an array

### ISSUE THREAD

**Issue by Xheldon** [octokit/core.js#648]
### What happened?

The type of 'data' field in OctokitResponse type is an object but type hinting show it's an array, as a result, I received a type error: 'sha' does not exist on the 'data' type.

see the image:

![CleanShot_2024_01_08_at_18_09_33@2x](https://github.com/octokit/core.js/assets/9780154/3af37e9a-1036-454e-aefd-f6a0212a6cb3)

![CleanShot_2024_01_08_at_18_14_48@2x](https://github.com/octokit/core.js/assets/9780154/e4c4a2df-242a-49cb-b6a6-fa1a47f50ab6)

### Versions

"octokit": "^3.1.2"
node -v v18.16.0

### Relevant log output

```shell
NO
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This is normal as the endpoint can return an array of objects depending on the media type.

https://docs.github.com/en/rest/using-the-rest-api/getting-started-with-the-rest-api?apiVersion=2022-11-28#media-types
