### ISSUE TITLE
OctokitOptions should provide a GraphQl specific base URL to support GHES.

### ISSUE THREAD

**Issue by thboop** [octokit/core.js#65]
The `baseUrl` field exists in `OctokitOptions` and provides the base URL to be used for both GraphQL and Rest. 

The urls for hosted are the same `api.github.com`

However, in GHES, these expect different values. The documentation shows the differing formats.

- https://github.com/octokit/core.js#defaults: `https://github.acme-inc.com/api/v3`
- https://github.com/octokit/graphql.js/#use-with-github-enterprise:  `https://github.acme-inc.com/api`

Ideally, I would like to
```
import {Core} from '@octokit/core'
const octokit = new Core({
  baseUrl: "https://github.acme-inc.com/api/v3",
  graphQLBaseUrl: "https://github.acme-inc.com/api"
})
// Call v3 and graphql apis


// or 

import {Core} from '@octokit/core'
const MyOctokit = Core.defaults({
  baseUrl: "https://github.acme-inc.com/api/v3",
  graphQLBaseUrl: "https://github.acme-inc.com/api"
})
```

But any way to set the baseUrl for both of these via `defaults` and have them correctly work on GHES would be fantastic 🙏

**Comment by gr2m** [comment]
I think I'll eventually change the way `baseUrl` works, and remove the `/api/v3` suffix. There are other API endpoints that don't use that. 

But for the time being, I think we should be able to derive the baseUrl for the `octokit.graphql` method from the current `baseUrl` option, without introducing a new one. I'm looking into it
