### ISSUE TITLE
[BUG]: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in 

### ISSUE THREAD

**Issue by IchanZX1** [octokit/core.js#667]
### What happened?

How To fix?

### Versions

Octokit.js v6.0.1, Node v18.19.1

### Relevant log output

```shell
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/container/node_modules/@octokit/core/package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:366:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:656:13)
    at resolveExports (node:internal/modules/cjs/loader:584:36)
    at Module._findPath (node:internal/modules/cjs/loader:658:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/container/index.js:31:21) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
Node.js v18.19.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
That specific error message suggest you are not using ESM.

Please see the usage section in the README: 
https://github.com/octokit/core.js?tab=readme-ov-file#usage

**Comment by clementhemidy** [comment]
Hi,

I have the same issue.

```
Error: No "exports" main defined in ***/node_modules/@octokit/core/package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:366:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:656:13)
    at resolveExports (node:internal/modules/cjs/loader:584:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:658:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1120:27)
    at Function.Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (***/src/github/github.repository.ts:1:1)
```

Octokit.js: v6.0.1
Node version: v18.19.1
Npm version: 10.2.4

**Comment by wolfy1339** [comment]
Are you using typescript at all? In typescript just because you are importing using ESM imports doesn't mean you are using ESM

**Comment by wolfy1339** [comment]
If anyone is experiencing this issue, please give a small reproducible example in a separate repo.

Include the `package.json` and the `tsconfig.json` as well as a file that has the least code in order to reproduce the problem.

Also don't forget to specify the environment (Browser/Node/Deno as well as the version)

It would be very helpful in diagnosing this issue and helping out users.

You may also want to read up on ESM packages, https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by iamnotstatic** [comment]
Anyone found a workaround for this, i'm also experiencing same issue

**Comment by wolfy1339** [comment]
> Anyone found a workaround for this, i'm also experiencing same issue 

@iamnotstatic Please read my comment above.
Please provide all relevant information

**Comment by Darker935** [comment]
@wolfy1339 https://github.com/Darker935/MdgWa-TEST

**Comment by wolfy1339** [comment]
@Darker935  `@octokit/rest` is not an ESM module yet, you will have to downgrade `@octokit/auth-token`

**Comment by iamnotstatic** [comment]
> > Anyone found a workaround for this, i'm also experiencing same issue
> 
> @iamnotstatic Please read my comment above. Please provide all relevant information

Downgrading to `5.1.0` worked fine for me i will just stick to that for now

**Comment by wolfy1339** [comment]
I understand that downgrading has solved the issue, I really wish to diagnose and fix this issue for users

**Comment by wolfy1339** [comment]
You are using CJS and not ESM. In typescript you **can** use ESM with CJS (though you can't mix ESM and CJS Octokit modules together due to upgraded dependencies introducing backwards incompatible changes)
with the following options you should be fine

```
    "target": "es2022",
     "module": "node16",
     "moduleResolution": "node16",
```

**Comment by iamnotstatic** [comment]
> You are using CJS and not ESM. In typescript you **can** use ESM with CJS (though you can't mix ESM and CJS Octokit modules together due to upgraded dependencies introducing backwards incompatible changes) with the following options you should be fine
> 
> ```
>     "target": "es2022",
>      "module": "node16",
>      "moduleResolution": "node16",
> ```

Alright thanks @wolfy1339

**Comment by JoaoScheleder** [comment]
@wolfy1339  I'm getting the same error and others, setting to ESM or "node16" in tsconfig
With: 
```
"target": "es2016"
"module": "commonjs"
```
Results in:
>[ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined 

With:
```
"target": "es2022"
"module": "es2022"
```
Case package.json type = "module":
>ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts".

Without package.json type = "module":
>SyntaxError: Cannot use import statement outside a module and Cannot find module '@octokit/core'. 

With:
```
"target": "es2022"
"module": "Node16"
```
Results in:  
>The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@octokit/core")' call instead. To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to 'C:/Users/{user}/project/package.json'.

My default tsconfig.json file:
```
{
  "compilerOptions": {
    "target": "ES2016",                                  /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */
    "module": "CommonJS",                                /* Specify what module code is generated. */
    "rootDir": "./",                                  /* Specify the root folder within your source files. */
    "outDir": "./dist",                                   /* Specify an output folder for all emitted files. */
    "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */    
    "strict": true,                                      /* Enable all strict type-checking options. */
    "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
  }
}
```
I'm using **"@octokit/core": "^6.0.1"**  and **Node v18.17.0** 
my import look like this:
```
import { Octokit } from "@octokit/core"
const octokit = new Octokit({ auth: env.GITHUB_TOKEN });
```

**Comment by wolfy1339** [comment]
You can use dynamic imports, upgrade your code to ESM, or stick with v5

Option 1:
```js
async function main() {
  const { Octokit } = await import('@octokit/core');

  const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
}
main();
```

Option 2: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
`tsconfig.json`:
```
"moduleResolution": "node16",
"module": "node16",
"target": "es2022"
```
`package.json`:
```
"type": "module"
```

Option 3:
`package.json`:
```
"@octokit/core": "^5"
```
---
The error in question in this issue is people that their code is CJS and are importing an ESM module.

There is also bugs with `ts-node` where it can't handle ESM: https://github.com/TypeStrong/ts-node/issues/2094 https://github.com/TypeStrong/ts-node/issues/2100

At this point, there is nothing actionable on our part. This is user error

**Comment by jeremy-daley-kr** [comment]
I don't think this should've been closed out. The resolution would be to add to all octokit `package.json` files:

```json
".": {
  "default": "path/to/entry.js"
}
```

So many packages I've seen in the wild omit [`default`](https://nodejs.org/api/packages.html#conditional-exports)

**Comment by wolfy1339** [comment]
From how I interpret the documentation, `default` doesn't seem needed. It should match `import`
Even with the `default`, it would still error as it's ESM and people are trying to import it in a CJS environment.

Do you have an explanation as to why thus isn't the case?

**Comment by JoaoScheleder** [comment]
I changed my package.json to type "module" and in my tsconfig i'm using: 
```   
"moduleResolution": "Node",
"module": "ES2022",
"target": "es2022", 
```
And it did help, but i was still getting an error.
> [!IMPORTANT]
> what helped me was switching from **nodemon** and **ts-node** to **tsx**. 
> my start script look like this:

```"start": "npx tsx watch index.ts"``` 
>like @wolfy1339 said, **ts-node** has some bugs :+1:

**Comment by wolfy1339** [comment]
> Is there a specific reason _not_ to include a fallback? What led me here to begin with is seeing this issue with `tsx` after upgrading `@octokit/core`, and adding `default` allowed the resolution.

There isn't any specific reason. It's just how I have interpreted the specs. Feel free to send in PRs

**Comment by wolfy1339** [comment]
I just released a new version with the fix as described by @jeremy-daley-kr 

Please open up a new issue if you still have issues.

**Comment by MihaelIsaev** [comment]
Is it CJS? I'm getting `octokit The current file is a CommonJS module` while trying to import it `import { Octokit, App } from "octokit";` after installing via `npm install octokit` in my newly create VSCode Extension.

My tsconfig:
```
{
	"compilerOptions": {
		"module": "Node16",
		"target": "ES2022",
		"lib": [
			"ES2022"
		],
		"sourceMap": true,
		"rootDir": "src",
		"strict": true
	}
}
```

**Comment by wolfy1339** [comment]
Nope it is not CJS. You haven't defined your file as an ESM module.

Either use the `.mjs` extension or specify `"type": "module"` in your `package.json`
